spring:
  datasource:
    url: jdbc:h2:mem:lifeskill
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

file:
  upload-dir: ./uploads

kakao:
  client-id: ${KAKAO_CLIENT_ID:e84ce356948e78dfda116f679826b51b}
  client-secret: ${KAKAO_CLIENT_SECRET:hTjfT4KxxaEAkRp8bquchnaU8RL9eC6Y}
  redirect-uri: http://localhost:3000/auth/kakao/callback
