spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres.aucboipkmqxkbiokvery
    password: ${DB_PASSWORD:Eowhdud123^^}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: never

file:
  upload-dir: /home/ec2-user/uploads

kakao:
  client-id: ${KAKAO_CLIENT_ID:e84ce356948e78dfda116f679826b51b}
  client-secret: ${KAKAO_CLIENT_SECRET:hTjfT4KxxaEAkRp8bquchnaU8RL9eC6Y}
  redirect-uri: ${KAKAO_REDIRECT_URI:https://www.gophysicaltraining.com/auth/kakao/callback}

cors:
  allowed-origins: ${CORS_ORIGINS:https://www.gophysicaltraining.com,https://gophysicaltraining.com}

server:
  port: 8080
